import Head from "next/head";
import MenuItem from "@/components/common/MenuItem";
import { useTranslation } from "next-i18next";

import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Image from "next/image";

import Link from "next/link";

import { Inter } from "@next/font/google";
import LocaleSwitcher from "@/components/language-switcher";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     


      <MenuItem />
    </>
  );
}

export async function getStaticProps({ locale }) {
  console.log("Locale:", locale);

  return {
    props: {
      ...(await serverSideTranslations(locale, ["menu-item"])),
    },
  };
}
